### ISSUE TITLE
Cannot connect from Opera and OBS  net::ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by OlegShklyarov** [victor7376/CB-Chat#1]
Hey! I am getting this error while trying to connect from Opera or OBS. 

Failed to load resource: net::ERR_CONNECTION_RESET
Error: TypeError: Failed to fetch

In Chrome it works fine. What to do?

**Comment by victor7376** [comment]
I’ll check tomorrow, are you using the built in vpn or an Adblocker by any chance?

**Comment by OlegShklyarov** [comment]
> I’ll check tomorrow, are you using the built in vpn or an Adblocker by any chance?

Definitely not. Just an average Antivirus. But it works on Chrome.

**Comment by OlegShklyarov** [comment]
Forgive me, I forgot that I have a proxy browser extension . It works, thanks

**Comment by victor7376** [comment]
> Forgive me, I forgot that I have a proxy browser extension . It works, thanks

Cheers for confirming the issue 😉
